using HtmlAgilityPack;
using Microsoft.Playwright;
using System.Collections;

namespace HitachiQA.Playwright
{
    public static class LocatorExtensions
    {
        public static async Task AssertIsPresentAsync(this ILocator locator)
        {
            await Assertions.Expect(locator.First).ToHaveCountAsync(1, new() { Timeout = 30000 });
        }
        public static async Task AssertIsVissibleAsync(this ILocator locator)
        {
            await Assertions.Expect(locator.First).ToBeVisibleAsync(new() { Timeout = 30000 });
        }
        public static async Task AssertNotVissibleAsync(this ILocator locator)
        {
            await Assertions.Expect(locator.First).Not.ToBeVisibleAsync(new() { Timeout = 30000 });
        }
        public static async Task<bool> ExistsAsync(this ILocator locator)
        {
            var count = await locator.CountAsync();
            return count > 0;
        }
        public static async Task AssertIsPresentAsync(this Task<ILocator> locatorTask)
        {
            var loc = await locatorTask;
            await loc.AssertIsPresentAsync();
        }

        public static async Task ClickAsync(this Task<ILocator> locatorTask)
        {
            var loc = await locatorTask;
            await loc.ClickAsync();
        }

        public static async Task<string> TextContentAsync(this Task<ILocator> locatorTask)
        {
            var loc = await locatorTask;
            return await loc.TextContentAsync();
        }

        public static async Task SetFieldValueAsync(this Task<ILocator> locatorTask, object value)
        {
            var loc = await locatorTask;
            await loc.SetFieldValueAsync(value);
        }

        public static async Task SetFieldValueAsync(this ILocator locator, object value)
        {
            var html = await locator.EvaluateAsync("el=>el.outerHTML");
            var fieldDoc = new HtmlDocument();
            fieldDoc.LoadHtml(html.ToString());
            KeyValuePair<string, string> matchingPair = FieldAutoDetector.FindKnownXPathMatchingPair(fieldDoc, locator);

            var autoGeneratedLocator = await GetAutoGeneratedLocator(locator, matchingPair);

            try
            {
                switch (matchingPair.Value)
                {
                    case "dropdown":
                        var dropdownOption = Convert.ToString(value) ?? throw new NullReferenceException();
                        await autoGeneratedLocator.SelectOptionAsync(dropdownOption);

                        break;
                    case "textfield":
                        var textFieldVal = Convert.ToString(value) ?? throw new NullReferenceException();
                        await autoGeneratedLocator.FillAsync(textFieldVal);
                        break;
                    case "button_dropdown":
                        var buttonDropdownVal = Convert.ToString(value) ?? throw new NullReferenceException();
                        var optionLocator = autoGeneratedLocator.Locator($"xpath=/following-sibling::*//button[normalize-space(text())='{value}']");
                        await autoGeneratedLocator.ClickAsync();
                        await optionLocator.ClickAsync();
                        break;
                    case "radio_buttons_group":
                        var radioButtonsGroupVal = Convert.ToString(value);
                        var radioButtonLocator = autoGeneratedLocator.Locator($"xpath=" +
                            $"//label[normalize-space(text())='{value}'][(following-sibling::input or preceding-sibling::input)] | " +
                            $"//input[@id='{value}' or normalize-space(text())='{value}']");
                        await radioButtonLocator.ClickAsync();
                        break;
                    case "checkboxes_group":
                        string[] checkList = [];
                        if (value is IEnumerable enumerable && value is not string)
                        {
                            checkList = enumerable.Cast<string>().ToArray();
                        }
                        else
                        {
                            var checkboxStr = Convert.ToString(value);
                            if (checkboxStr.Contains(';'))
                            {
                                checkList = checkboxStr.Split(';').Select(s => s.Trim()).ToArray();
                            }
                            else
                            { 
                                checkList = [Convert.ToString(value)];
                            }
                        }

                        foreach (var item in checkList)
                        {
                           var checkboxLocator = autoGeneratedLocator.Locator($"xpath=" +
                                $"//label[normalize-space(text())='{item}'][(following-sibling::input or preceding-sibling::input)] | " +
                                $"//input[@id='{item}' or normalize-space(text())='{item}']");
                            await checkboxLocator.ClickAsync();
                        }
                        break;
                    default: throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        public static async Task<string> GetFieldValueAsync(this Task<ILocator> locatorTask)
        {
            var loc = await locatorTask;
            return await loc.GetFieldValueAsync();
        }
        public static async Task<T> GetFieldValueAsync<T>(this Task<ILocator> locatorTask)
        {
            var loc = await locatorTask;
            return await loc.GetFieldValueAsync<T>();
        }

        public static async Task<string> GetFieldValueAsync(this ILocator locator)
        {
            return await locator.GetFieldValueAsync<string>();
        }

        public static async Task<T> GetFieldValueAsync<T>(this ILocator locator)
        {
            var html = await locator.EvaluateAsync("el=>el.outerHTML");
            var fieldDoc = new HtmlDocument();
            fieldDoc.LoadHtml(html.ToString());
            KeyValuePair<string, string> matchingPair = FieldAutoDetector.FindKnownXPathMatchingPair(fieldDoc, locator);

            var autoGeneratedLocator = await GetAutoGeneratedLocator(locator, matchingPair);
            string value = null;
            try
            {
                switch (matchingPair.Value)
                {
                    case "dropdown":
                        value = await autoGeneratedLocator.EvaluateAsync<string>("select => select.options[select.selectedIndex].text");
                        break;
                    case "textfield":
                        value = await autoGeneratedLocator.InputValueAsync();
                        break;
                    case "button_dropdown":
                        value = await autoGeneratedLocator.InnerTextAsync();
                        value = value.Trim();
                        break;
                    case "radio_buttons_group":
                        var radioButtonLocator = autoGeneratedLocator.Locator($"xpath=//input[@type='radio']");
                        var all_radio = await radioButtonLocator.AllAsync();
                        foreach(var loc in all_radio)
                        {
                            var isChecked = await loc.IsCheckedAsync();
                            if(isChecked)
                            {
                                var text = await loc.InnerTextAsync();
                                if(string.IsNullOrWhiteSpace(text))
                                {
                                    text = await loc.Locator("xpath=following-sibling::*").InnerTextAsync();
                                }
                                value = text;
                                break;
                            }
                        }
                        break;
                    case "checkboxes_group":
                        var checkBoxLocator = autoGeneratedLocator.Locator($"xpath=//input[@type='checkbox']");
                        var all_checkboxes = await checkBoxLocator.AllAsync();
                        var checkedBoxes = new List<string>();
                        foreach (var loc in all_checkboxes)
                        {
                            var isChecked = await loc.IsCheckedAsync();
                            if (isChecked)
                            {
                                var text = await loc.InnerTextAsync();
                                if (string.IsNullOrWhiteSpace(text))
                                {
                                    text = await loc.Locator("xpath=following-sibling::*").InnerTextAsync();
                                }
                                checkedBoxes.Add(text);
                            }
                        }
                        if (typeof(IEnumerable).IsAssignableFrom(typeof(T)) && typeof(T) != typeof(string))
                        {
                            return (T)(object)checkedBoxes.ToList(); // Convert to List<T> or similar
                        }
                        else
                        {
                            value = string.Join(";", checkedBoxes);
                        }
                        break;
                    default: throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
                }

                return (T)Convert.ChangeType(value, typeof(T));
            }
            catch (Exception)
            {
                throw;
            }
        }

        private static async Task<ILocator> GetAutoGeneratedLocator(ILocator locator, KeyValuePair<string, string> matchingPair)
        {
            var newLocator = locator.Locator($"xpath={matchingPair.Key}");
            var newLocatorCount = await newLocator.CountAsync();
            if (newLocatorCount == 0)
            {
                return locator;
            }
            return newLocator;
        }


    }
}
