using HtmlAgilityPack;
using Microsoft.Playwright;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HitachiQA.Source.Playwright
{
    public static class LocatorExtensions
    {
        public static async Task AssertIsPresentAsync(this ILocator locator)
        {
            await Assertions.Expect(locator.First).ToHaveCountAsync(1);
        }
        public static async Task AssertIsVissibleAsync(this ILocator locator)
        {
            await Assertions.Expect(locator.First).ToBeVisibleAsync();
        }
        public static async Task AssertNotVissibleAsync(this ILocator locator)
        {
            await Assertions.Expect(locator.First).Not.ToBeVisibleAsync();
        }

        public static async Task SetFieldValueAsync(this ILocator locator, object value)
        {
            var html = await locator.EvaluateAsync("el=>el.outerHTML");
            var fieldDoc = new HtmlDocument();
            fieldDoc.LoadHtml(html.ToString());
            KeyValuePair<string, string> matchingPair = FieldAutoDetector.FindKnownXPathMatchingPair(fieldDoc, locator);

            var autoGeneratedLocator = await GetAutoGeneratedLocator(locator, matchingPair);

            try
            {
                switch (matchingPair.Value)
                {
                    case "dropdown":
                        var dropdownOption = Convert.ToString(value) ?? throw new NullReferenceException();
                        await autoGeneratedLocator.SelectOptionAsync(dropdownOption);

                        break;
                    case "textfield":
                        var textFieldVal = Convert.ToString(value) ?? throw new NullReferenceException();
                        await autoGeneratedLocator.FillAsync(textFieldVal);

                        break;
                    default: throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        private static async Task<ILocator> GetAutoGeneratedLocator(ILocator locator, KeyValuePair<string, string> matchingPair)
        {
            var newLocator = locator.Locator($"xpath={matchingPair.Key}");
            var newLocatorCount = await newLocator.CountAsync();
            if (newLocatorCount == 0)
            {
                return locator;
            }
            return newLocator;
        }


    }
}
