<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<RunSettingsFilePath>$(MSBuildProjectDirectory)\default.runsettings</RunSettingsFilePath>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UserSecretsId>7b85a15c-3a25-45e6-9b9e-df20af5954a9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="7.0.0" />
	  <PackageReference Include="HitachiQA" Version="1.8.7-2025011122" />
	  <PackageReference Include="Microsoft.Fabric.Api" Version="1.0.0-beta.30" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="Microsoft.Playwright" Version="1.49.0" />
    <PackageReference Include="Microsoft.Playwright.MSTest" Version="1.49.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.1" />
	  <PackageReference Include="Reqnroll.MsTest" Version="2.4.1" />
	  <PackageReference Include="Reqnroll.Tools.MsBuild.Generation" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
