# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  project: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
  - stage: NugetPush
    jobs:
      - deployment: InternalArtifactPush
        displayName: 'Nuget - Publish packages to internal feed'
        environment: InternalArtifactPush
        strategy:
          runOnce:
            deploy:
              steps: 
                - download: none

      - job:
        steps:
        - checkout: none


        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'specific'
            pipeline: '6'
            specificBuildWithTriggering: true
            buildVersionToDownload: specific
            buildId: $(Build.SourceVersion)
            branchName: '$(Build.SourceBranch)'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.DefaultWorkingDirectory)'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'push'
            packagesToPush: '**/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'c2ea9fd3-e9a8-4690-bac9-7c3063ac1e20'