# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  project: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  name: $(Date:yyyyMMdd)$(Rev:.r)

resources:
  pipelines:
  - pipeline: BuildPipeline # identifier for the resource (used in pipeline resource variables)
    source: "HitachiQA.Build"

stages:
  - stage: NugetPush
    jobs:
      - deployment: InternalArtifactPush
        displayName: 'Nuget - Publish packages to internal feed'
        environment: InternalArtifactPush
        strategy:
          runOnce:
            deploy:
              steps: 
                - download: none

      - job:
        steps:
        - checkout: none

        - task: DownloadPipelineArtifact@2
          inputs:
            artifactName: 'drop'
            pipelineResource: 'BuildPipeline'
            branchName: '$(Build.SourceBranch)'
            buildType: specific
            buildVersionToDownload: specific
            downloadPath: '$(System.DefaultWorkingDirectory)'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'push'
            packagesToPush: '**/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'c2ea9fd3-e9a8-4690-bac9-7c3063ac1e20'