trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: TargetServiceConnection
    displayName: Target Service Connection
    type: string
    default: Biberk_MA_ServiceConnection
    values:
    - Biberk_MA_ServiceConnection
    - CPI_SV_ServiceConnection
    - Deere_MA_ServiceConnection

jobs:
  - job: 
    steps:
    - template: azure-pipelines.downloadbuild.template.yml
    - task: NuGetAuthenticate@1
      inputs:
        nuGetServiceConnections: ${{ parameters.TargetServiceConnection }}

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: ${{ parameters.TargetServiceConnection }}