using HitachiQA.Helpers;
using HtmlAgilityPack;
using OpenQA.Selenium;
using OpenQA.Selenium.Interactions;
using Polly;

namespace HitachiQA.Driver
{
    public partial class UserActions
    {
        public string GetFieldValue(By[] by)
        {
            waitForPageLoad(by.First().IFrameLocator);
            WaitForTransaction();

            var fieldElement = this.FindElementWaitUntilPresent(by, out var resultLocator);
            var fieldDoc = new HtmlDocument();
            fieldDoc.LoadHtml(fieldElement.GetAttribute("outerHTML"));


            KeyValuePair<string, string> matchingPair = FieldAutoDetector.FindKnownXPathMatchingPair(fieldDoc, out HtmlNode node, resultLocator.ToString());
            matchingPair.NullGuard();

            var autoGeneratedLocator = GetAutoGeneratedLocator(resultLocator, matchingPair);

            String fieldValue = null;
            switch (matchingPair.Value)
            {
                case "dropdown":
                    fieldValue = GetSelectedDropdownValue(autoGeneratedLocator);
                    break;
                case "textfield_autocomplete":
                    fieldValue = this.getTextFieldText(autoGeneratedLocator);

                    break;
                case "mat-autocomplete":
                    fieldValue = this.getTextFieldText(autoGeneratedLocator);
                    break;
                case "textfield":
                    fieldValue = this.getTextFieldText(autoGeneratedLocator);
                    break;
                case "lookup_with_selection":
                    fieldValue = this.getElementText(autoGeneratedLocator.Select(l => By.XPath(l.Locator.Criteria + "/*", by.First().IFrameLocator)).ToArray());
                    break;
                case "lookup_with_dialog":
                    fieldValue = this.getTextFieldText(autoGeneratedLocator);
                    break;
                case "lookup":
                    fieldValue = this.getTextFieldText(autoGeneratedLocator);
                    break;
                case "switch":
                    throw new NotImplementedException("switch getter not implemented yet");
                case "lookup_with_table":
                    fieldValue = this.getTextFieldText(autoGeneratedLocator);
                    break;
                case "mat-select":
                    var currentValContainer = autoGeneratedLocator.Select(l => By.XPath($"{l.Locator.Criteria} //*[contains(@class, 'mat-select-value')]//*[text()]", l.IFrameLocator)).ToArray();
                    fieldValue = FindElementWaitUntilVisible(currentValContainer).Text;
                    break;
                case "checkbox":
                    fieldValue = this.GetCheckboxState(autoGeneratedLocator).ToString();
                    break;
                case "datepicker":
                    fieldValue = GetDatePickerFieldValue(autoGeneratedLocator);
                    break;
                case "input_with_combobox":
                    fieldValue = this.getTextFieldText(autoGeneratedLocator);
                    break;
                case "textfieldreadonly":
                    fieldValue = this.getTextFieldText(autoGeneratedLocator);
                    break;
                default: throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
            }

            if (fieldValue == null)
            {
                throw new Exception($"error while getting field value of field located by {Log.stringify(by)}");
            }
            return fieldValue;
        }

        public void SetFieldValue(By by, string value) => SetFieldValue(by, value);

        public void SetFieldValue(By[] by, string value)
        {
            this.waitForPageLoad(by.First().IFrameLocator);
            this.WaitForTransaction();

            var fieldElement = this.FindElementWaitUntilPresent(by, out var resultingLocator);
            var fieldDoc = new HtmlDocument();
            fieldDoc.LoadHtml(fieldElement.GetAttribute("outerHTML"));


            KeyValuePair<string, string> matchingPair = FieldAutoDetector.FindKnownXPathMatchingPair(fieldDoc, out HtmlNode node, resultingLocator.ToString());
            matchingPair.NullGuard();

            var autoGeneratedLocator = GetAutoGeneratedLocator(resultingLocator, matchingPair);

            try
            {


                switch (matchingPair.Value)
                {
                    case "dropdown":
                        this.SelectDropdownValue(autoGeneratedLocator, value);
                        break;
                    case "textfield_autocomplete":
                        this.setText(autoGeneratedLocator, value);
                        var autoCompleteItemLoc = By.XPath("//section[contains(@id, 'fieldControl')] //li");
                        this.FindElementWaitUntilClickable(autoCompleteItemLoc).Click();
                        break;
                    case "textfield":
                        this.setText(autoGeneratedLocator, value);
                        break;
                    case "lookup_with_selection":
                        new Actions(this.WebDriver).MoveToElement(this.FindElementWaitUntilPresent(autoGeneratedLocator)).Perform();
                        var removeButtonLocator = autoGeneratedLocator.Select(l => By.XPath(l.Locator.Criteria + "/following-sibling::button", by.First().IFrameLocator)).ToArray();
                        this.FindElementWaitUntilPresent(removeButtonLocator).Click();
                        var lookupPath = FieldAutoDetector.KnownXPaths.First(it => it.Value == "lookup").Key;
                        autoGeneratedLocator = autoGeneratedLocator.Select(l => By.XPath($"{l.Locator.Criteria} {lookupPath}", l.IFrameLocator)).ToArray();
                        performLookupValueSet(autoGeneratedLocator, value);
                        break;
                    case "lookup":
                        performLookupValueSet(autoGeneratedLocator, value);
                        break;
                    case "switch":
                        var switchVal = parseStrIntoBool(value);
                        var element = FindElementWaitUntilClickable(autoGeneratedLocator);

                        if (bool.Parse(element.GetAttribute("aria-checked")) != switchVal)
                            element.Click();
                        break;
                    case "lookup_with_table":
                        this.setText(autoGeneratedLocator, value);
                        //index=1 is the header and index=2 is the first row
                        this.Click(By.XPath("//form[contains(@class, 'lookup-popup active-form')]//*[@role='row' and @aria-rowindex='2']"));
                        break;
                    case "lookup_with_dialog":
                        this.Click(autoGeneratedLocator.Select(l => By.XPath(l.Locator.Criteria + "/following-sibling::*//*[@class='fa fa-search']", l.IFrameLocator)).ToArray());
                        this.SetFieldValue(By.XPath("//*[@id='lookupDialogRoot'] //input[contains(@id, 'lookupDialogLookup')]"), value);
                        this.Click(By.XPath("//*[@id='lookupDialogRoot'] //button[@aria-label ='Add']"));
                        break;
                    case "checkbox":
                        var checkboxVal = parseStrIntoBool(value);
                        if (checkboxVal != this.GetCheckboxState(autoGeneratedLocator))
                        {
                            try
                            {
                                Click(autoGeneratedLocator);
                            }
                            catch (ElementClickInterceptedException)
                            {
                                Click(autoGeneratedLocator.Select(l => By.XPath(l.Locator.Criteria + "/..", l.IFrameLocator)).ToArray());
                            }

                        }
                        break;
                    case "effective_grid_lookup":

                        this.Click(autoGeneratedLocator.Select(l => By.XPath(l.Locator.Criteria + "//input[@type='submit']", l.IFrameLocator)).ToArray());
                        var lookupIframe = By.XPath("//iframe[contains(@id, 'hisol-dialog')]");
                        this.setText(By.XPath("//*[@class='lookupDialogContainer']//input[@type='text']", lookupIframe), value);
                        this.Click(By.XPath("//*[contains(@class,'crmSearchIcon')]", lookupIframe));
                        this.Click(By.XPath("(//tr//input[@type='checkbox'])[1]", lookupIframe));
                        this.Click(By.XPath("//button[text()='Ok']", lookupIframe));

                        break;
                    case "numerictextbox":
                        fieldElement.Click();
                        var numericTextBox = this.FindElementWaitUntilPresent(autoGeneratedLocator);
                        numericTextBox.Clear();
                        fieldElement.Click();
                        numericTextBox.SendKeys(value);
                        // this.JSExecutor.execute($"arguments[0].value={value}", numericTextBox);
                        break;
                    case "combobox":
                        this.Click(autoGeneratedLocator);
                        var targetOption = By.XPath($"(//button[contains(@class,'dropdownItem') and .//*[text()='{value}']]) | //*[contains(@class, 'ms-Checkbox') and @title='{value}']");
                        this.Click(targetOption);
                        break;
                    case "datepicker":

                        //
                        //Date
                        //
                        var targetDate = DateTime.Parse(value);
                        this.SetDatePickerValue(autoGeneratedLocator, targetDate);
                        //
                        //Time
                        //

                        var timeLocator = by.Select(l => By.XPath($"({l.Locator.Criteria})//input[contains(@aria-label,'Time')]", l.IFrameLocator)).ToArray();
                        if (this.FindElementWaitUntilPresent(timeLocator, 1, true) != null)
                        {
                            this.setText(timeLocator, targetDate.ToString("hh:mm tt"));
                        }

                        break;
                    case "dropdown_listbox":
                        this.Click(autoGeneratedLocator);
                        this.Click(By.XPath($"//div[@data-role='popup' and contains(@style,'display: block')]//li[normalize-space()='{value}']", autoGeneratedLocator.First().IFrameLocator));
                        break;
                    case "input_with_combobox":
                        this.setText(autoGeneratedLocator, value);
                        this.Click(By.XPath("//*[contains(@class,'suggestions')]//button", autoGeneratedLocator.First().IFrameLocator));
                        break;
                    case "enum_combobox":
                        this.Click(autoGeneratedLocator);
                        var option = By.XPath($"//*[contains(@class,'calloutMain')] //input[@type='checkbox' and @title='{value}']/..", autoGeneratedLocator.First().IFrameLocator);
                        this.Click(option);
                        break;
                    case "mat-autocomplete":
                        this.setText(autoGeneratedLocator, value);
                        var matAutCompItemLoc = By.XPath($"//mat-option[descendant::*[normalize-space(text())= '{value}']]");
                        if (!ElementExists(matAutCompItemLoc))
                        {
                            matAutCompItemLoc = By.XPath($"//mat-option");
                        }
                        Click(matAutCompItemLoc);
                        break;
                    case "mat-select":
                        this.SelectMatDropdownOptionByText(autoGeneratedLocator, value);
                        break;
                    case "bh-question-singleselect":
                        var radio_Locator = By.XPath(autoGeneratedLocator.First().Locator.Criteria + $"//mat-radio-button[.//*[normalize-space(text())='{value}']]");
                        var radio_inputLocator = By.XPath(autoGeneratedLocator.First().Locator.Criteria + $"//mat-radio-button[.//*[normalize-space(text())='{value}']]//*[contains(@class,'radio-touch-target')]");

                        var radio_Retry =
                            Policy
                            .HandleResult<bool>(false)
                            .WaitAndRetry(5, _ => TimeSpan.FromSeconds(1));

                        var clicked = radio_Retry.Execute(() =>
                        {
                            DoubleClick(radio_inputLocator);
                            return FindElementWaitUntilPresent(radio_Locator).GetAttribute("class").Contains("radio-checked");
                        });

                        if (!clicked)
                            throw new Exception("\nFailed to click: \n" + radio_inputLocator + "\n");


                        break;
                    default: throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");

                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Error setting value for \n{Log.stringify(resultingLocator)}\n matched pair {matchingPair.Value}={matchingPair.Key}", ex);
            }
            this.waitForPageLoad(autoGeneratedLocator.First().IFrameLocator);
            this.WaitForTransaction();
        }

        public static bool parseStrIntoBool(string input)
        {
            input = input.ToLower();
            switch (input)
            {
                case "1":
                case "yes":
                case "true":
                case "check":
                    return true;
                case "0":
                case "no":
                case "false":
                case "uncheck":
                    return false;
                default:
                    throw new NotImplementedException("Invalid input value. Expected values for true: 1, yes, true, check. Expected values for false: 0, no, false, uncheck.");
            }
        }

        private By[] GetAutoGeneratedLocator(By matchingLocator, KeyValuePair<string, string> matchingPair)
        {

            return new[]{
                By.XPath($"({matchingLocator.Locator.Criteria}) {matchingPair.Key}", matchingLocator.IFrameLocator),
                By.XPath($"({matchingLocator.Locator.Criteria})", matchingLocator.IFrameLocator)
            };
        }

        private void performLookupValueSet(By[] autoGeneratedLocator, string value)
        {
            Thread.Sleep(500);
            this.setText(autoGeneratedLocator, value);
            var searchButton = autoGeneratedLocator.Select(l => By.XPath(l.Locator.Criteria + "/following-sibling::button", l.IFrameLocator)).ToArray();
            this.FindElementWaitUntilClickable(searchButton).Click();
            var itemLocator = By.XPath("//ul[@aria-label='Lookup results'] //li[@aria-label]", autoGeneratedLocator.First().IFrameLocator);
            this.FindElementWaitUntilClickable(itemLocator).Click();
        }


        private string GetDatePickerFieldValue(By[] autoGeneratedLocator)
        {
            var date = this.getTextFieldText(autoGeneratedLocator.Select(l => By.XPath($"({l.Locator.Criteria}//input)[1]", l.IFrameLocator)).ToArray());
            var timeElement = autoGeneratedLocator.Select(l => By.XPath($"({l.Locator.Criteria}//input)[2]", l.IFrameLocator)).ToArray();
            var time = "";
            if (ElementExists(timeElement))
            {
                time = this.getTextFieldText(timeElement);
            }
            var dateTime = DateTime.Parse(date + " " + time);
            return dateTime.ToString("O");
        }

        public List<string> GetFieldOptions(By[] by)
        {
            this.WaitForTransaction();
            this.waitForPageLoad(by.First().IFrameLocator);
            var fieldElement = this.FindElementWaitUntilPresent(by, out var resultLocator);
            var fieldDoc = new HtmlDocument();
            fieldDoc.LoadHtml(fieldElement.GetAttribute("outerHTML"));


            KeyValuePair<string, string> matchingPair = FieldAutoDetector.FindKnownXPathMatchingPair(fieldDoc, out var _, resultLocator.ToString());
            matchingPair.NullGuard();

            var autoGeneratedLocator = GetAutoGeneratedLocator(resultLocator, matchingPair);

            List<string> options = null;
            switch (matchingPair.Value)
            {
                case "dropdown":
                    options = GetDropdownOptionsText(autoGeneratedLocator);
                    break;
                case "textfield_autocomplete":
                    throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
                case "mat-autocomplete":
                    throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
                case "lookup_with_selection":
                    throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
                case "lookup":
                    throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
                case "lookup_with_table":
                    throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
                case "mat-select":
                    options = this.GetAllMatDropdownOptions(autoGeneratedLocator).ToList();
                    break;
                default: throw new NotImplementedException($"Method for field type {matchingPair.Value} has not been implemented");
            }

            if (options == null)
            {
                throw new Exception($"error while getting field value of field located by {Log.stringify(by)}");
            }
            return options;
        }


        public void OpenFieldValue(By[] by)
        {
            this.WaitForTransaction();
            this.waitForPageLoad(by.First().IFrameLocator);

            var fieldElement = this.FindElementWaitUntilPresent(by, out var resultLocator);
            var fieldDoc = new HtmlDocument();
            fieldDoc.LoadHtml(fieldElement.GetAttribute("outerHTML"));


            KeyValuePair<string, string> matchingPair = FieldAutoDetector.FindKnownXPathMatchingPair(fieldDoc, out var _, resultLocator.ToString());
            matchingPair.NullGuard();

            var autoGeneratedLocator = GetAutoGeneratedLocator(resultLocator, matchingPair);

            switch (matchingPair.Value)
            {
                case "dropdown":
                    throw new NotImplementedException($"OpenFieldValue: Method for field type {matchingPair.Value} has not been implemented");
                case "textfield_autocomplete":
                    throw new NotImplementedException($"OpenFieldValue: Method for field type {matchingPair.Value} has not been implemented");
                case "mat-autocomplete":
                    throw new NotImplementedException($"OpenFieldValue: Method for field type {matchingPair.Value} has not been implemented");
                case "lookup_with_selection":
                    Click(autoGeneratedLocator);
                    break;
                case "lookup":
                    throw new NotImplementedException($"OpenFieldValue: Method for field type {matchingPair.Value} has not been implemented");
                case "lookup_with_table":
                    throw new NotImplementedException($"OpenFieldValue: Method for field type {matchingPair.Value} has not been implemented");
                case "mat-select":
                    throw new NotImplementedException($"OpenFieldValue: Method for field type {matchingPair.Value} has not been implemented");
                default: throw new NotImplementedException($"OpenFieldValue: Method for field type {matchingPair.Value} has not been implemented");
            }

        }

    }
}
