# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - master
    
pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  project: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorPackageOutputdir: '$(Build.ArtifactStagingDirectory)/packages/major'
  minorPackageOutputdir: '$(Build.ArtifactStagingDirectory)/packages/minor'

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      displayName: 'Build Test Publish'
      steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
                $xml = [Xml](Get-Content .\HitachiQA\HitachiQA.csproj)
                $version = $xml.Project.PropertyGroup.Version
                
                $versionArr = $version.Split('.')
                $nextPatch = ([int]versionArr[-1])
                $nextPatch++
                $nextVersion = '$versionArr[0].$versionArr[1].$nextPatch'
                
                $buildId = "$(Build.BuildNumber)" -replace "\.", ""
                $minorReleaseVersion = "$nextVersion+$buildId"

                Write-Host "##[section]MajorReleaseVersion: $version"
                Write-Host "##[section]MinorReleaseVersion: $minorReleaseVersion"

                # Set the versions as Azure Pipeline variables
                Write-Host "##vso[task.setvariable variable=MajorReleaseVersion]$version"
                Write-Host "##vso[task.setvariable variable=MinorReleaseVersion]$minorReleaseVersion"

        - template: templates/build.template.yml
        - template: templates/run-tests.template.yml

        - task: DotNetCoreCLI@2
          displayName: 'HitachiQA pack minor release'
          inputs:
            command: 'pack'
            packagesToPack: '**/HitachiQA.csproj'
            outputDir: '$(minorPackageOutputdir)'
            versioningScheme: 'byEnvVar'
            versionEnvVar: "MinorReleaseVersion"
            includesource: true

        - task: DotNetCoreCLI@2
          displayName: 'Builder pack minor release'
          inputs:
            command: 'pack'
            packagesToPack: '**/Hsl.HitachiQA.Builder.csproj'
            outputDir: '$(minorPackageOutputdir)'
            versioningScheme: 'byEnvVar'
            versionEnvVar: "MinorReleaseVersion"
            includesource: true

        - task: DotNetCoreCLI@2
          displayName: 'pack major release HitachiQA'
          inputs:
            command: 'pack'
            packagesToPack: '**/HitachiQA.csproj'
            outputDir: '$(majorPackageOutputdir)'
            versioningScheme: 'off'

        - task: DotNetCoreCLI@2
          displayName: 'pack major release Builder'
          inputs:
            command: 'pack'
            packagesToPack: '**/Hsl.HitachiQA.Builder.csproj'
            outputDir: '$(majorPackageOutputdir)'
            versioningScheme: 'off'

        - template: templates/publish.template.yml

     