# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  project: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
  - stage: NugetPush
    jobs:
      - job:
        steps:
        - checkout: none
        - template: ./templates/downloadbuild.template.yml
        - task: DotNetCoreCLI@2
          inputs:
            command: 'push'
            packagesToPush: '**/*.nupkg; !**/*.symbols.nupkg;'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'c2ea9fd3-e9a8-4690-bac9-7c3063ac1e20'
            arguments: '--skip-duplicate'