# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'
    
stages:
  - stage: Test
    pool: 
      vmImage: 'windows-latest'
    jobs:
    - job:
      steps:
      - template: 'templates/build.template.yml'

      - template: templates/run-tests.template.yml
        parameters:
          filter: TestCategory=dynamics.fs
          runTitle: "Dynamics FS Unit Tests"
          runsettings: dynamics.fs.runsettings
