# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: MajorRelease
    displayName: Push as major release
    type: boolean
    default: false

stages:
  - stage: NugetPush
    jobs:
      - job:
        steps:
        - checkout: none
        - template: ./templates/downloadbuild.template.yml

        - task: DotNetCoreCLI@2
          condition: 'not(${{ parameters.MajorRelease }})'
          displayName: 'Push Minor Release'
          inputs:
            command: 'push'
            packagesToPush: '**/minor/*.nupkg; !**/*.symbols.nupkg;'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'ae37399a-6d13-479d-85f6-0257203b84b1'
            arguments: '--skip-duplicate'

        - task: DotNetCoreCLI@2
          condition: '${{ parameters.MajorRelease }}'
          displayName: 'Push Major Release'
          inputs:
            command: 'push'
            packagesToPush: '**/major/*.nupkg; !**/*.symbols.nupkg;'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'ae37399a-6d13-479d-85f6-0257203b84b1'
            arguments: '--skip-duplicate'
            