# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - master
    
pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: MajorRelease
    displayName: Build a major release
    type: boolean
    default: false

variables:
  solution: '**/*.sln'
  project: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      displayName: 'Build Test Publish'
      steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
                $xml = [Xml](Get-Content .\HitachiQA\HitachiQA.csproj)
                $version = $xml.Project.PropertyGroup.Version

                # Extract major and minor parts of the version
                if ($version -match '^(\d+\.\d+)(?:\.\d+)?$') {
                    $majorMinorVersion = $matches[1] # This will capture "1.x" from "1.x.x"
                } else {
                    Write-Error "Version format is not recognized: $version"
                    exit 1
                }

                $buildId = "$(Build.BuildNumber)" -replace "\.", ""
                $minorReleaseVersion = "$majorMinorVersion.$buildId"

                echo "MajorReleaseVersion $majorMinorVersion"
                echo "MinorReleaseVersion $minorReleaseVersion"

                # Set Azure DevOps pipeline variables
                echo "##vso[task.setvariable variable=MajorReleaseVersion]$majorMinorVersion"
                echo "##vso[task.setvariable variable=MinorReleaseVersion]$minorReleaseVersion"

        - template: templates/build.template.yml
        - template: templates/run-tests.template.yml

        - task: DotNetCoreCLI@2
          condition: 'not(${{ parameters.MajorRelease }})'
          displayName: 'HitachiQA pack minor release'
          inputs:
            command: 'pack'
            packagesToPack: '**/HitachiQA.csproj'
            outputDir: '$(Build.ArtifactStagingDirectory)/packages'
            versioningScheme: 'byEnvVar'
            versionEnvVar: "MinorReleaseVersion"
            includesource: true

        - task: DotNetCoreCLI@2
          condition: 'not(${{ parameters.MajorRelease }})'
          displayName: 'Builder pack minor release'
          inputs:
            command: 'pack'
            packagesToPack: '**/Hsl.HitachiQA.Builder.csproj'
            outputDir: '$(Build.ArtifactStagingDirectory)/packages'
            versioningScheme: 'byEnvVar'
            versionEnvVar: "MinorReleaseVersion"
            includesource: true

        - task: DotNetCoreCLI@2
          condition: ${{ parameters.MajorRelease }}
          displayName: 'pack major release HitachiQA'
          inputs:
            command: 'pack'
            packagesToPack: '**/HitachiQA.csproj'
            outputDir: '$(Build.ArtifactStagingDirectory)/packages'
            versioningScheme: 'off'

        - task: DotNetCoreCLI@2
          condition: ${{ parameters.MajorRelease }}
          displayName: 'pack major release Builder'
          inputs:
            command: 'pack'
            packagesToPack: '**/Hsl.HitachiQA.Builder.csproj'
            outputDir: '$(Build.ArtifactStagingDirectory)/packages'
            versioningScheme: 'off'

        - template: templates/publish.template.yml

     