# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
  - pipeline: BuildPipeline # identifier for the resource (used in pipeline resource variables)
    source: "HitachiQA.Build"

stages:
  - download: BuildPipeline 
    artifact: drop

  - stage: Test
    pool: 
      vmImage: 'windows-latest'
    jobs:
      - template: ./templates/downloadbuild.template.yml

      - job: 
        steps:
        - checkout: none
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/HitachiQA.UnitTests.dll'
            arguments: '--settings $(System.DefaultWorkingDirectory)/drop/HitachiQA.UnitTests/default.runsettings --no-build --filter TestCategory!=Dynamics'
            testRunTitle: 'HitachiQA Unit Tests'
