# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - '*.yml'
    
pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: MajorRelease
    displayName: Build a major release
    type: boolean
    default: false

variables:
  solution: '**/*.sln'
  project: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      displayName: 'Build Test Publish'
      steps:
        - template: templates/build.template.yml
        - template: templates/run-tests.template.yml

        - task: DotNetCoreCLI@2
          condition: 'not(${{ parameters.MajorRelease }})'
          displayName: 'pack'
          inputs:
            command: 'pack'
            projects: '$(solution)'
            searchPatternPack: '$(project)'
            nobuild: true
            outputDir: '$(System.DefaultWorkingDirectory)'
            versioningScheme: 'byPrereleaseNumber'
            majorVersion: '1'
            minorVersion: '0.1'
            includesource: true

        - task: DotNetCoreCLI@2
          condition: ${{ parameters.MajorRelease }}
          displayName: 'pack'
          inputs:
            command: 'pack'
            projects: '$(solution)'
            searchPatternPack: '$(project)'
            nobuild: true
            outputDir: '$(System.DefaultWorkingDirectory)'
            versioningScheme: off

        - template: templates/publish.template.yml

     