trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'


parameters:
  - name: TargetServiceConnection
    displayName: Target Service Connection
    type: string
    default: MMO_MS_ServiceConnection
    values:
    - BB_MS_ServiceConnection
    - CPI_SV_ServiceConnection
    - Deere_MA_ServiceConnection
    - RKH_FA_ServiceConnection
    - MMO_MS_ServiceConnection

  - name: MajorRelease
    displayName: Push as major release
    type: boolean
    default: false

jobs:
  - job: 
    steps:
    - checkout: none
    - template: ./templates/downloadbuild.template.yml
    - task: NuGetAuthenticate@1
      inputs:
        nuGetServiceConnections: ${{ parameters.TargetServiceConnection }}

    - task: NuGetCommand@2
      displayName: 'Push minor Release'
      condition: 'not(${{ parameters.MajorRelease }})'
      inputs:
        command: 'push'
        packagesToPush: '**/minor/*.nupkg; !**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: ${{ parameters.TargetServiceConnection }}
    
    - task: NuGetCommand@2
      displayName: 'Push major Release'
      condition: '${{ parameters.MajorRelease }}'
      inputs:
        command: 'push'
        packagesToPush: '**/major/*.nupkg; !**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: ${{ parameters.TargetServiceConnection }}