//import { app, BrowserWindow } from 'electron';
import { app, BrowserWindow, dialog, ipcMain, session, shell } from 'electron'
import { OpenDialogOptions } from 'electron/main';
import { InvocationResult, PowerShell } from 'node-powershell';
import path from 'path';
import { readFile } from 'fs/promises';
import { existsSync, mkdirSync} from 'fs';



// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

var mainWindow : BrowserWindow

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 700,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: true
    },
    frame: false,
    icon: './images/squarelogo.png'
  }); 
  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  // Customize protocol to handle static resource.
  session.defaultSession.protocol.registerFileProtocol('static', (request: any, callback:any) => {
    const fileUrl = request.url.replace('static://', '');
    const filePath = path.join(app.getAppPath(), '.webpack/renderer', fileUrl);
    callback(filePath);
  });

  createWindow();
});


// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.handle('dialog:openFile', handleFileOpen)
ipcMain.handle('script:run', runScript)
ipcMain.handle('app:close', closeApp)
ipcMain.handle('app:minimize', minimizeApp)
ipcMain.handle('file:readme', getReadme)
ipcMain.handle('validate:toolInstalled', validateCommandLineToolInstalled)
ipcMain.handle('devTools:open', openDevTools)
ipcMain.handle("info:loadDefaults", loadDefaults)
ipcMain.handle('open-browser', (event, url) => {
  shell.openExternal(url);
});

async function runScript(event: any, script: string): Promise<InvocationResult> {
  const ps = new PowerShell({
    debug: false, // Disable debug logs to avoid unnecessary output
    executableOptions: {
      '-ExecutionPolicy': 'Bypass',
      '-NoProfile': true,
      '-NonInteractive': false,
    },
  });

  console.log('PowerShell instance created.');
  console.log('Running script:', script);

  return new Promise<InvocationResult>((resolve, reject) => {
    // Listen for stdout events
    ps.streams.stdout.on('data', (data: string) => {
      event.sender.send('powershell-output', data.trim()); // Send to renderer process
    });

    // Listen for stderr events
    ps.streams.stderr.on('data', (data: string) => {
      event.sender.send('powershell-error', data.trim()); // Send to renderer process
    });

    // Invoke the script
    ps.invoke(script)
      .then((result: InvocationResult) => {
        event.sender.send('powershell-done', 0); // Send success event
        resolve(result); // Return the full InvocationResult
      })
      .catch((err: Error) => {
        event.sender.send('powershell-done', 1); // Send failure event
        reject(err); // Reject with the error
      })
      .finally(() => {
        ps.dispose(); // Dispose of the PowerShell instance
      });
  });
}




async function handleFileOpen () {
  const options:OpenDialogOptions = {
    properties: ['openDirectory'],
  };

  const { canceled, filePaths } = await dialog.showOpenDialog(options)
  if (canceled) {

  } else {
    return filePaths[0]
  }
}

async function getReadme(event: any):Promise<string> {

  
  const filePath = path.join(app.getAppPath(), '.webpack/renderer', "assets/README.md");
  return readFile(filePath, 'utf8');

  
}

async function validateCommandLineToolInstalled(event: any, toolInvokingName: string) {
  const ps = new PowerShell({
    debug: true,
    executableOptions: {
      '-ExecutionPolicy': 'Bypass',
      '-NoProfile': true,
    }
  });

  let results = await ps.invoke(`${toolInvokingName} --version`).catch((e)=> {
      return e;
  });
  console.log(results);
  if("hadErrors" in results)
  {
    if(!results.hadErrors)
    {
      return true;
    }
  }
  return false;
}

function openDevTools(event: any)
{
    mainWindow.webContents.openDevTools();

}

function closeApp () {
  app.quit();
}
function minimizeApp () {
  mainWindow.minimize();
}

async function loadDefaults(event: any) {
  const ps = new PowerShell({
    debug: true,
    executableOptions: {
      '-ExecutionPolicy': 'Bypass',
      '-NoProfile': true,
      '-NonInteractive': true, // Ensure it runs in non-interactive mode
    },
  });

  const outputPath = path.join(app.getAppPath(), '.webpack/renderer/assets/versions.json');
  const command = `hitachiqabuilder info -o "${outputPath}"`;

  try {
    // Ensure the assets directory exists
    const assetsDir = path.dirname(outputPath);
    if (!existsSync(assetsDir)) {
      mkdirSync(assetsDir, { recursive: true });
    }

    console.log("executing", command);
    await ps.invoke(command); // Run the command

    // Read the JSON file and return its contents
    const fileContents = await readFile(outputPath, 'utf8');
    return JSON.parse(fileContents);
  } catch (error) {
    console.error('Error running hitachiqabuilder info:', error);
    throw error;
  }
}