//import { app, BrowserWindow } from 'electron';
import { app, BrowserWindow, dialog, ipcMain, session } from 'electron'
import { OpenDialogOptions } from 'electron/main';
import { PowerShell } from 'node-powershell';
import path from 'path';
import { readFile } from 'fs/promises';



// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

var mainWindow : BrowserWindow

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 700,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: true
    },
    frame: false
  }); 
  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  
  // Open the DevTools.
  //mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  // Customize protocol to handle static resource.
  session.defaultSession.protocol.registerFileProtocol('static', (request: any, callback:any) => {
    const fileUrl = request.url.replace('static://', '');
    const filePath = path.join(app.getAppPath(), '.webpack/renderer', fileUrl);
    callback(filePath);
  });

  createWindow();
});


// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.handle('dialog:openFile', handleFileOpen)
ipcMain.handle('script:run', runScript)
ipcMain.handle('script:runBuild', runBuildScript)
ipcMain.handle('app:close', closeApp)
ipcMain.handle('app:minimize', minimizeApp)
ipcMain.handle('file:readme', getReadme)
ipcMain.handle('validate:toolInstalled', validateCommandLineToolInstalled)

async function runBuildScript(event: any, script: string){
  const rendererPath = path.join(app.getAppPath(), '.webpack/renderer')
  const assets = path.join(app.getAppPath(), '.webpack/renderer/assets')
  script = script+` -assetsDir ${assets}`
  const filePath = path.join(rendererPath, script)

  console.log(filePath)
  return await runScript(event, filePath)
}

async function runScript(event: any, script: string){
  const ps = new PowerShell({
    debug: true,
    executableOptions: {
      '-ExecutionPolicy': 'Bypass',
      '-NoProfile': true,
      "-NonInteractive": true
    }});
  

  let result = await ps.invoke(script).catch(e=> {
      return e;
      }
    )
  return result;
}


async function handleFileOpen () {
  const options:OpenDialogOptions = {
    properties: ['openDirectory'],
  };

  const { canceled, filePaths } = await dialog.showOpenDialog(options)
  if (canceled) {

  } else {
    return filePaths[0]
  }
}

async function getReadme(event: any):Promise<string> {

  
  const filePath = path.join(app.getAppPath(), '.webpack/renderer', "assets/README.md");
  return readFile(filePath, 'utf8');

  
}

async function validateCommandLineToolInstalled(event: any, toolInvokingName: string) {
  const ps = new PowerShell({
    debug: true,
    executableOptions: {
      '-ExecutionPolicy': 'Bypass',
      '-NoProfile': true,
    }
  });

  let results = await ps.invoke(`${toolInvokingName} --version`).catch((e)=> {
      return e;
  });
  console.log(results);
  if("hadErrors" in results)
  {
    if(!results.hadErrors)
    {
      return true;
    }
  }
  return false;
}


function closeApp () {
  app.quit();
}
function minimizeApp () {
  mainWindow.minimize();
}

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
